name: Setup pnpm and node.js for CI/CD
description: This action sets up pnpm and node.js for CI/CD workflows.

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '11'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@v6
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile