name: Manual 02
on:
    workflow_dispatch:
        inputs:
            log_level:
                description: "Nivel de log"
                required: true
                default: "info"
                type: choice
                options: 
                    - info
                    - debug
                    - warn
                    - error

            environment:
                description: "Entorno"
                type: environment
            
            dry_run:
                description: "Ejecutar si aplicar los cambios"
                required: false
                default: false
                type: boolean

            reason: 
                description: "Motivo de la ejecucion"
                required: false
                default: "Manual execution"
                type: string

jobs: 
    manual:
        runs-on: ubuntu-24.04
        steps:
            - name: Saludar
              run: echo "Hola desde Github Actions!"
            
            - name: Ver fecha del runner
              run: date
            
            - name: Ver archivos disponibles
              run: ls -la