name: Manual 02
on:
    workflow_dispatch:
        inputs:
            log_level:
                description: "Nivel de log"
                required: true
                default: "info"
                type: choice
                options: 
                    - info
                    - debug
                    - warn
                    - error

            environment:
                description: "Entorno"
                type: environment
            
            dry_run:
                description: "Ejecutar si aplicar los cambios"
                required: false
                default: false
                type: boolean

            reason: 
                description: "Motivo de la ejecucion"
                required: false
                default: "Manual execution"
                type: string

jobs: 
    manual:
        runs-on: ubuntu-24.04
        steps:
            - name: Mostrar todos los inputs
              env:
                LOG_LEVEL: ${{ github.event.inputs.log_level }}
                ENVIRONMENT: ${{ github.event.inputs.environment }}
                DRY_RUN: ${{ github.event.inputs.dry_run }}
                REASON: ${{ github.event.inputs.reason }}
              run: |
                echo "Log Level: $LOG_LEVEL"
                echo "Environment: $ENVIRONMENT"
                echo "Dry Run: $DRY_RUN"
                echo "Reason: $REASON"
            
            - name: Deploy (solo si no es dry-run)
              if: ${{ !inputs.dry_run }}
              run: |
                echo "Desplegando cambios..."
                # Aquí iría el comando real de despliegue
