name: 03 - Schedule

on: 
    schedule:
        - cron: '0 0 * * *' # Ejecutar todos los

jobs:
    schedule: 
        runs-on: ubuntu-24.04
        steps:
            - name: Saludar
              run: echo "¡Hola, desde Github Actions!"