name: 05 - CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11 
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: 
          cd 09-ci-cd
          echo "::group::Linting frontend"
          pnpm lint:frontend
          echo "::endgroup::"

    frontend-test:
      runs-on: ubuntu-24.04

      defaults:
        run:
          working-directory: 09-ci-cd

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up pnpm
          uses: pnpm/action-setup@v6
          with:
            version: 11 
            run_install: false

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Test
          run: pnpm test:frontend
        
  backend-lint:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11 
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: 09-ci-cd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11 
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test:backend
